name = "AstroCouch"
uuid = "49c2c03a-1c99-4e96-bd03-21227f8707f2"
version = "0.1.0"
authors = ["Tamas Gal <tamas.gal@fau.de> and contributors"]

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
Polynomials = "4"
StaticArrays = "1.9.14"
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
